import { Header } from "@/components/Shared/Header";
import { BlogApiProvider } from "@/context/api.provider";
import UserProvider from "@/context/user.provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "../globals.css";
import getSession from "@/actions/user.action";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getSession()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <BlogApiProvider>
            <Header isLoggedIn={!!session?.user?.email} />
            {children}
          </BlogApiProvider>
        </UserProvider>
        <Toaster />
      </body>
    </html>
  );
}
